DROP TABLE IF EXISTS "booking" CASCADE;
DROP TABLE IF EXISTS "booking_logs" CASCADE;
DROP TABLE IF EXISTS "cabs" CASCADE;
DROP TABLE IF EXISTS "admin" CASCADE;
DROP TABLE IF EXISTS "drivers" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP VIEW IF EXISTS detailed_bookings;
DROP FUNCTION IF EXISTS log_booking_status_change();

CREATE TABLE "users" (
  "user_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "phone" varchar(15),
  "email" varchar(50) UNIQUE,
  "password" varchar(50)
);

CREATE TABLE "drivers" (
  "driver_id" int PRIMARY KEY,
  "name" varchar(50),
  "phone" varchar(15),
  "license_no" varchar(50),
  "email" varchar(50) UNIQUE,
  "password" varchar(50)
);

CREATE TABLE "admin" (
  "admin_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) NOT NULL,
  "password" varchar(50) NOT NULL
);

CREATE TABLE "cabs" (
  "cab_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cab_number" varchar(20),
  "cab_type" varchar(20),
  "driver_id" int,
  "ac_type" varchar(10) DEFAULT 'AC',
  CONSTRAINT "cabs_driver_fk" FOREIGN KEY ("driver_id") REFERENCES "drivers" ("driver_id")
);

CREATE TABLE "booking" (
  "booking_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "cab_id" int,
  "pickup_location" varchar(100),
  "drop_location" varchar(100),
  "booking_date" date,
  "booking_time" time,
  "status" varchar(20) DEFAULT 'Confirmed',
  CONSTRAINT "booking_user_fk" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id"),
  CONSTRAINT "booking_cab_fk" FOREIGN KEY ("cab_id") REFERENCES "cabs" ("cab_id")
);

CREATE TABLE "booking_logs" (
  "log_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_id" int NOT NULL,
  "old_status" varchar(20),
  "new_status" varchar(20),
  "changed_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "booking_logs_booking_fk" FOREIGN KEY ("booking_id") REFERENCES "booking" ("booking_id")
);

CREATE VIEW detailed_bookings AS
SELECT
  b.booking_id,
  b.user_id,
  b.cab_id,
  b.pickup_location,
  b.drop_location,
  b.booking_date,
  b.booking_time,
  b.status,
  u.name AS user_name,
  u.phone AS user_phone,
  u.email,
  c.cab_number,
  c.cab_type,
  d.name AS driver_name,
  d.phone AS driver_phone,
  d.license_no
FROM booking AS b
LEFT JOIN users AS u ON u.user_id = b.user_id
LEFT JOIN cabs AS c ON c.cab_id = b.cab_id
LEFT JOIN drivers AS d ON d.driver_id = c.driver_id;

CREATE TABLE "booking_logs" (
  "log_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_id" int NOT NULL,
  "old_status" varchar(20),
  "new_status" varchar(20),
  "changed_at" timestamp DEFAULT now(),
  CONSTRAINT "logs_booking_fk" FOREIGN KEY ("booking_id") REFERENCES "booking" ("booking_id") ON DELETE CASCADE
);

CREATE OR REPLACE FUNCTION log_booking_status_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO "booking_logs" ("booking_id", "old_status", "new_status", "changed_at")
  VALUES (NEW."booking_id", OLD."status", NEW."status", now());
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS booking_status_audit_trigger ON "booking";
CREATE TRIGGER booking_status_audit_trigger
AFTER UPDATE ON "booking"
FOR EACH ROW
WHEN (OLD."status" IS DISTINCT FROM NEW."status")
EXECUTE FUNCTION log_booking_status_change();

CREATE INDEX "booking_user_id_idx" ON "booking" ("user_id");
CREATE INDEX "booking_cab_id_idx" ON "booking" ("cab_id");
CREATE INDEX "cabs_driver_id_idx" ON "cabs" ("driver_id");
