DROP TABLE IF EXISTS "booking" CASCADE;
DROP TABLE IF EXISTS "cabs" CASCADE;
DROP TABLE IF EXISTS "admin" CASCADE;
DROP TABLE IF EXISTS "drivers" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

CREATE TABLE "users" (
  "user_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "phone" varchar(15),
  "email" varchar(50) UNIQUE,
  "password" varchar(50)
);

CREATE TABLE "drivers" (
  "driver_id" int PRIMARY KEY,
  "name" varchar(50),
  "phone" varchar(15),
  "license_no" varchar(50),
  "email" varchar(50) UNIQUE,
  "password" varchar(50)
);

CREATE TABLE "admin" (
  "admin_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) NOT NULL,
  "password" varchar(50) NOT NULL
);

CREATE TABLE "cabs" (
  "cab_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cab_number" varchar(20),
  "cab_type" varchar(20),
  "driver_id" int,
  "ac_type" varchar(10) DEFAULT 'AC',
  CONSTRAINT "cabs_driver_fk" FOREIGN KEY ("driver_id") REFERENCES "drivers" ("driver_id")
);

CREATE TABLE "booking" (
  "booking_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "cab_id" int,
  "pickup_location" varchar(100),
  "drop_location" varchar(100),
  "booking_date" date,
  "booking_time" time,
  "status" varchar(20) DEFAULT 'Confirmed',
  CONSTRAINT "booking_user_fk" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id"),
  CONSTRAINT "booking_cab_fk" FOREIGN KEY ("cab_id") REFERENCES "cabs" ("cab_id")
);

CREATE INDEX "booking_user_id_idx" ON "booking" ("user_id");
CREATE INDEX "booking_cab_id_idx" ON "booking" ("cab_id");
CREATE INDEX "cabs_driver_id_idx" ON "cabs" ("driver_id");
